spring.application.name=lab3-api-gateway
server.port=3000

# URLs base de los microservicios que componen el sistema
modulos.estudiantes.url=http://localhost:3001
modulos.materias.url=http://localhost:3002
modulos.inscripciones.url=http://localhost:3003

# JWT
jwt.secreto=OpktG6lpOZJ0SV8SGAVeRI43IBMhLYE5
jwt.expiracion-minutos=60

logging.level.root=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %5p [%t] %c - %m%n
