spring.application.name=lab3-api-gateway
server.port=8080

# URLs base de los microservicios que componen el sistema
modulos.estudiantes.url=http://localhost:8081
modulos.materias.url=http://localhost:8082
modulos.inscripciones.url=http://localhost:8083

# JWT
jwt.secreto=CAMBIA_ESTA_LLAVE_POR_UNA_PROPIA_DE_AL_MENOS_32_CARACTERES_LARGA
jwt.expiracion-minutos=60

logging.level.root=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %5p [%t] %c - %m%n
